[Config Exp4_PubSub]
network = smarthome.SmartHomeNetwork
sim-time-limit = 300s
repeat = 5
seed-set = ${repetition}

**.arp.typename = "GlobalArp"
*.radioMedium.backgroundNoise.power = -110dBm
*.configurator.addStaticRoutes = true

# ---------------- Sensors publish data directly, no request needed ----------------
*.temp*.numApps = 1
*.temp*.app[0].typename = "UdpBasicApp"
*.temp*.app[0].destAddresses = "monitoringApp"
*.temp*.app[0].destPort = 5000
*.temp*.app[0].sendInterval = ${I = 1s, 5s, 10s, 30s}
*.temp*.app[0].messageLength = 50B
*.temp*.app[0].packetName = "PublishData"
*.temp*.app[0].startTime = uniform(0s, ${I})

*.motion*.numApps = 1
*.motion*.app[0].typename = "UdpBasicApp"
*.motion*.app[0].destAddresses = "monitoringApp"
*.motion*.app[0].destPort = 5000
*.motion*.app[0].sendInterval = ${I}
*.motion*.app[0].messageLength = 50B
*.motion*.app[0].packetName = "PublishData"
*.motion*.app[0].startTime = uniform(0s, ${I})

# ---------------- Monitoring app is the broker/subscriber ----------------
*.monitoringApp.numApps = 1
*.monitoringApp.app[0].typename = "UdpSink"
*.monitoringApp.app[0].localPort = 5000

**.vector-recording = false
**.scalar-recording = true
